<div class="container">
  <div class="row m-5">
    <div class="col">
      <h3><i class="bi bi-file-text text-primary me-3"></i> Web Content</h3>
      <div class="row">
        <span class="mb-5 text-secondary col-8">This module is used to manage content of MGM Lab website. The content is generated by using a markdown editor, which is based on a plain-text text editor and the actual content is rendered using a markdown parser to HTML page.</span>
        <span class="col-4 text-end">
          <a class="bt-new-content btn btn-primary"><i class="bi bi-plus-lg me-2"></i>Create New Content</a>
        </span>
      </div>
      <form id="form-search" class="pb-3 border-bottom">
        <div class="input-group mb-3">
          <input type="text" name="keyword" class="form-control w-50 input-keyword" placeholder="Search keyword" aria-label="Keyword">
          <select name="perpage" class="form-select flex-shrink-1 input-perpage">
            <option value="1">1</option>
            <option value="5">5</option>
            <option value="10" selected="">10</option>
            <option value="25">25</option>
            <option value="50">50</option>
            <option value="100">100</option>
            <option value="200">200</option>
            <option value="300">300</option>
            <option value="500">500</option>
            <option value="1000">1000</option>
          </select>
          <button class="btn btn-secondary bt-search"><i class="bi bi-search"></i></button>
        </div>
        <!-- <div class="border rounded bg-light p-3">
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="prodi-d3" value="D3">
            <label class="form-check-label" for="prodi-d3">D3 Kebidanan</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="prodi-d3f" value="D3F">
            <label class="form-check-label" for="prodi-d3f">D3 Farmasi</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="prodi-mik" value="MIK">
            <label class="form-check-label" for="prodi-mik">D4 Manajemen Informasi Kesehatan</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="prodi-fis" value="FIS">
            <label class="form-check-label" for="prodi-fis">D4 Fisioterapi</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="prodi-none" value="">
            <label class="form-check-label text-danger" for="prodi-none">Tanpa Prodi</label>
          </div>
        </div> -->
      </form>
      <div class="content-list mb-3"></div>
      <div class="content-pagination"></div>

      <hr class="my-5">

      <h3><i class="bi bi-plus-lg me-3 text-primary"></i>
        <span class="form-title">New Content</span>
      </h3>

      <div class="container px-5 my-5">
        <form id="content-form" class="needs-validation" novalidate>
          <input type="hidden" id="cid" name="cid" value="">

          <div class="form-floating mb-3">
            <input class="form-control" id="title" type="text" placeholder="Title" data-sb-validations="required" required />
            <label for="title">Title</label>
            <div class="invalid-feedback">Title is required.</div>
          </div>
          <div class="form-floating mb-3">
            <input class="form-control" id="subtitle" type="text" placeholder="Sub-title (Optional)" />
            <label for="subtitle">Sub-title (Optional)</label>
          </div>
          <div class="row g-3 mb-3">
            <div class="col">
              <div class="form-floating">
                <input class="form-control" id="key" type="text" placeholder="Key" required />
                <label for="key">Content Key</label>
                <div class="invalid-feedback">Key is required.</div>
              </div>
            </div>
            <div class="col d-flex align-items-center px-3 rounded border bg-light me-2">
              <div class="px-3">
                <label class="form-label-inline me-3 fw-bold">Content Type</label>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" id="type_md" type="radio" name="type" value="md" checked />
                    <label class="form-check-label" for="type_md">Markdown</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" id="type_html" type="radio" name="type" value="html" />
                    <label class="form-check-label" for="type_html">HTML</label>
                </div>
              </div>
            </div>
          </div> 
          <div class="mb-3">

            <code-input template="syntax-highlighted" class="rounded fs-5" language="html"></code-input>
            <textarea class="form-control" id="content" type="text" placeholder="Content" style="height: 10rem;" data-sb-validations="required"></textarea>

          </div>
          <div class="d-none" id="submitSuccessMessage">
            <div class="text-center mb-3">
              <div class="fw-bolder">Form submission successful!</div>
            </div>
          </div>
          <div class="d-none" id="submitErrorMessage">
            <div class="text-center text-danger mb-3">Error sending message!</div>
          </div>
          <div class="text-end">
            <button class="bt-clear btn btn-secondary btn-lg px-5 me-2" id="clearButton" type="button">Clear</button>
            <button class="btn btn-primary btn-lg px-5" id="submitButton" type="submit">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>